### ISSUE TITLE
Aggregate/visualize not working (because of empty output?)

### ISSUE THREAD

**Issue by Rubbert** [epigen/enrichment_analysis#18]
These jobs remain:
<img width="803" alt="image" src="https://github.com/epigen/enrichment_analysis/assets/5180191/9564a34b-947e-44a2-8fc9-75abe541b8e8">

Potentially because of empty combined files(?):
<img width="1656" alt="image" src="https://github.com/epigen/enrichment_analysis/assets/5180191/49821601-3fec-4432-a4ab-556a93096c06">

The individual outputs are not empty:
<img width="1659" alt="image" src="https://github.com/epigen/enrichment_analysis/assets/5180191/6d53dc64-72d1-4504-b0da-79351a6e0a93">

Maybe because nothing is significant?

**Comment by sreichl** [comment]
can't reproduce. maybe solved with next release (coming soon) with local GREAT usage. Empty results are accounted for across the workflow. Please let me know if something doesn't work with the next release.
